### ISSUE TITLE
401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by Andrii-Kalyniuk** [stravalib/stravalib#152]
Hello. Help me to understand, please.
I'm trying to create activity manually. But the following code crashes with an error.

Code:
```
from stravalib import Client
print("Connecting to Strava")
client = Client()
access_token = "3*84"
client.access_token = access_token
athlete = client.get_athlete()
print("Now authenticated for " + athlete.firstname + " " + athlete.lastname)
print("For {id}, I now have an access token {token}".format(id=athlete.id, token=access_token))
client.create_activity(
    name = 'Manual create activity Name testing Strava_API ',
    start_date_local = '2018-05-19T00:00:00Z',
    elapsed_time = 2700,
    distance = 1000.0,
    description = 'Description Name for testing Strava_API',
    activity_type = 'Run'
    )
```

Output:
```
No such attribute subscription_permissions on entity <Athlete id=3*1 firstname=A*i lastname=K*k>
Now authenticated for A*i K*k
For 3*1, I now have an access token 3*84
Traceback (most recent call last):
  File "K:\Ego\c0d3_own\Python\csv2strava.py", line 19, in <module>
    activity_type = 'Run'
  File "k:\Distrib\Coding\Python36\lib\site-packages\stravalib\client.py", line 549, in create_activity
    raw_activity = self.protocol.post('/activities', **params)
  File "k:\Distrib\Coding\Python36\lib\site-packages\stravalib\protocol.py", line 255, in post
    return self._request(url, params=params, files=files, method='POST', check_for_errors=check_for_errors, use_webhook_server=use_webhook_server)
  File "k:\Distrib\Coding\Python36\lib\site-packages\stravalib\protocol.py", line 170, in _request
    self._handle_protocol_error(raw)
  File "k:\Distrib\Coding\Python36\lib\site-packages\stravalib\protocol.py", line 215, in _handle_protocol_error
    raise x
requests.exceptions.HTTPError: 401 Client Error: Unauthorized [Authorization Error: [{'resource': 'AccessToken', 'field': 'write_permission', 'code': 'missing'}]]]
```

**Comment by hozn** [comment]
From that error message, I assume the problem is that this access token does not include write permissions:  when athlete A*i K*k granted permission to your application, they need to check the box that says [something like] "write allowed".

**Comment by alistair0adams** [comment]
I had the same problem. It did not resolve till I changed the code in the above example:

from:
client = Client()
access_token = "3*84"
client.access_token = access_token

to:
client = Client()
access_token = client.exchange_code_for_token(
    client_id=client_id,
    client_secret=client_secret,
    code=access_token
)

**Comment by fabthegreat** [comment]
Hello @alistair0adams ,

your snippet doesn't work (anymore?) since i get this error performing:
```
client = Client()
access_token = "3*84"
access_token = client.exchange_code_for_token(
client_id=client_id,
client_secret=client_secret,
code=access_token
```
the error looks like:
`stravalib.exc.Fault: 400 Client error: Bad request`

An idea?

**Comment by alistair0adams** [comment]
@fabthegreat This was a one of use so I haven't looked at it since. Just make sure you have entered the correct access_token, client_id, client_secret from the credentials that you got when you create the strava app id. Don't use "3*84" verbatim, that's just an example.
