### ISSUE TITLE
Exception raised parsing response from create_activity

### ISSUE THREAD

**Issue by pedropombeiro** [stravalib/stravalib#235]
It seems that there is a problem decoding the response from `create_activity`:

```
Traceback (most recent call last):
  File "/Users/pedropombeiro/src/github.com/huserben/walkingpad/restserver.py", line 610, in app_factory
    stravaClient.create_activity('Walking Pad', 'Walk', session_start_time, int((datetime.now() -
  File "/opt/homebrew/lib/python3.9/site-packages/stravalib/client.py", line 598, in create_activity
    raw_activity = self.protocol.post('/activities', **params)
  File "/opt/homebrew/lib/python3.9/site-packages/stravalib/protocol.py", line 304, in post
    return self._request(url, params=params, files=files, method='POST', check_for_errors=check_for_errors)
  File "/opt/homebrew/lib/python3.9/site-packages/stravalib/protocol.py", line 223, in _request
    resp = raw.json()
  File "/opt/homebrew/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
```

**Comment by lwasser** [comment]
hey there @pedropombeiro  👋 

i'm working through some of our older issues. We have implemented a significant API update and as such i'm curious if this issue is still a problem for you. 

if it is, please provide us with a bit more information in the form of a code sample that we can run locally. 
if i don't hear from you in the next week i will go ahead and close this. 

You can always reopen in the case that you miss my message and are still struggling with this!
