### ISSUE TITLE
Stravalib RELEASE 1.0  --> PyPI

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#267]
Hi everyone. 
This will be our first release in a really long time. 
And we have grown our maintainer team which is allowing us to chip away at more issues! 🎆 

[Click here to see  what stravalib will look like on PyPI](https://test.pypi.org/project/stravalib/). You can also install it to test version using:

`pip install -i https://test.pypi.org/simple/ stravalib`

I think the following TODO's are left
- [ ] Update the changelog to include fixes, updates and contributors to this release 
- [ ] Merge that PR
- [ ] Create a tagged release 1.0
- [ ] That release/tag will then trigger a deployment to pypi
- [ ] TEST the pypi deployment as it will be the first deployment in a long time and using a new build and package structure

-------
Note once we have done this I plan to submit a documentation PR that will clarify all of this in our docs. 

Am I missing anything? are we good to release stravalib v1.0 ?

**Comment by yihong0618** [comment]
looks great

**Comment by lwasser** [comment]
thanks @yihong0618 !!!

**Comment by jsamoocha** [comment]
Can it be that the [documentation](https://stravalib.readthedocs.io/en/latest/) is not updated? It still shows the old (0.6.0) docs. I have no idea where to look for a potential cause.

**Comment by lwasser** [comment]
oh it totally can. i need to redirect the build to the new location /stravalib/stravalib @jsamoocha would you like to have access to the doc build too? you'd just need an account on readthedocs.org and i can add you. i'll fix this now.

**Comment by jsamoocha** [comment]
I see this in the output of the action:

```
make docs -B
[3](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:3)
  shell: /usr/bin/bash -e {0}
[4](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:4)
  env:
[5](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:5)
    PYTHON-VERSION: 3.10
[6](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:6)
    pythonLocation: /opt/hostedtoolcache/Python/3.10.8/x64
[7](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:7)
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.8/x64/lib/pkgconfig
[8](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:8)
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.8/x64
[9](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:9)
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.8/x64
[10](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:10)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.8/x64
[11](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:11)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.8/x64/lib
[12](https://github.com/stravalib/stravalib/actions/runs/3525279450/jobs/5911802394#step:8:13)
make: Nothing to be done for 'docs'.
```

Shouldn't the command be `make -C docs -B`?

**Comment by jsamoocha** [comment]
When running the latter command locally (from project root), I see:

```
make -C docs -B
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v5.3.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/jsamoocha/.local/share/virtualenvs/stravalib-iclcMJAK/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/Users/jsamoocha/dev/stravalib/docs/conf.py", line 30, in <module>
    import stravalib
  File "/Users/jsamoocha/dev/stravalib/stravalib/__init__.py", line 4, in <module>
    from ._version import __version__
  File "/Users/jsamoocha/dev/stravalib/stravalib/_version.py", line 7, in <module>
    from . import _version_generated
ImportError: cannot import name '_version_generated' from partially initialized module 'stravalib' (most likely due to a circular import) (/Users/jsamoocha/dev/stravalib/stravalib/__init__.py)

make: *** [html] Error 2
```

Am I missing something that's not in version control?

**Comment by lwasser** [comment]
there are two issues here. The docs build doesn't actually push the docs to readthedocs, read the docs builds on it's own. The actions build is failing for the same reason that readthedocs is failing. 

We have to `build` that package and allow setuptools_Scm to create that _version_generated.py file that contains the single source truth for package version based upon the latest tag. Right now the docs need the same update that the tests had. But read the docs is a bit different so I need to look to see if we can build the package there too. 

Previously i had setup the docs to push directly to gh pages and to host them here vs on read the docs. I moved the docs to read the docs only because it saves older versions.  Let me look at this more closely tonight and we can open an issue about it. it's the one thing in all of this that i forgot about.  Below is the build OUTPUT from read the docs which is automated on a merge to master. 

<img width="865" alt="Screen Shot 2022-11-22 at 12 31 06 PM" src="https://user-images.githubusercontent.com/7649194/203404668-a73ad00b-9e3a-4c9a-8720-db26a94e8e0e.png">
